NUM_RECORDS = 10
PAGE_HEADER = NUM_RECORDS
NUM_PAGES = 10 
CHARS = 20
FIELDS = 12
PAGE_SIZE_WITHOUT_HEADER = CHARS * FIELDS * NUM_RECORDS
PAGE_SIZE = PAGE_SIZE_WITHOUT_HEADER + NUM_RECORDS
RECORD_SIZE = CHARS * FIELDS